// <auto-generated />
using System;
using BackendServer.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendServer.Data.Migrations
{
    [DbContext(typeof(BHPNTDbContext))]
    [Migration("20230606065353_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.AnnexContract", b =>
                {
                    b.Property<string>("HDPL")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("FromDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HDBH")
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("InsuranceFee")
                        .IsRequired()
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool?>("NewOrRenewed")
                        .IsRequired()
                        .HasColumnType("boolean");

                    b.Property<int?>("NumberOfPayments")
                        .HasColumnType("integer");

                    b.Property<decimal?>("STBH")
                        .IsRequired()
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TVTTCode")
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ToDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("HDPL");

                    b.HasIndex("HDBH");

                    b.HasIndex("TVTTCode");

                    b.ToTable("AnnexContracts", (string)null);
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.Branch", b =>
                {
                    b.Property<string>("BranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("BranchCode");

                    b.ToTable("Branchs", (string)null);
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.Collateral", b =>
                {
                    b.Property<string>("Ref")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AddressCollateral")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatusCollateral")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ValueCollateral")
                        .IsRequired()
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Ref");

                    b.ToTable("Collaterals", (string)null);
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.Customer", b =>
                {
                    b.Property<string>("Cif")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CustomerType")
                        .HasColumnType("integer")
                        .HasColumnName("CustomerType");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Cif");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.InfoCBNV", b =>
                {
                    b.Property<string>("TVTTCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameTVTT")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("TVTTCode");

                    b.HasIndex("BranchCode");

                    b.ToTable("InfoCBNVs", (string)null);
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.InsuranceContract", b =>
                {
                    b.Property<string>("HDBH")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Beneficiaries")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Cif")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CollateralRef")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("FromDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("InsuranceFee")
                        .IsRequired()
                        .HasColumnType("real");

                    b.Property<string>("InsuranceType")
                        .HasColumnType("text");

                    b.Property<string>("NewOrRenewed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfPayments")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("PartnerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float?>("STBH")
                        .IsRequired()
                        .HasColumnType("real");

                    b.Property<string>("TVTTCode")
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ToDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("HDBH");

                    b.HasIndex("Cif");

                    b.HasIndex("CollateralRef");

                    b.HasIndex("PartnerCode");

                    b.HasIndex("TVTTCode");

                    b.ToTable("InsuranceContracts", (string)null);
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.Partner", b =>
                {
                    b.Property<string>("PartnerCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("PartnerCode");

                    b.ToTable("Partners", (string)null);
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.PaymentPeriod", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("FeePaymentDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HDBH")
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Money")
                        .IsRequired()
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TotalAmount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HDBH");

                    b.ToTable("PaymentPeriods", (string)null);
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.AnnexContract", b =>
                {
                    b.HasOne("BaoHiemPhiNhanTho.BackendServer.Models.InsuranceContract", "InsuranceContract")
                        .WithMany("AnnexContracts")
                        .HasForeignKey("HDBH");

                    b.HasOne("BaoHiemPhiNhanTho.BackendServer.Models.InfoCBNV", "InfoCBNV")
                        .WithMany("AnnexContracts")
                        .HasForeignKey("TVTTCode");

                    b.Navigation("InfoCBNV");

                    b.Navigation("InsuranceContract");
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.InfoCBNV", b =>
                {
                    b.HasOne("BaoHiemPhiNhanTho.BackendServer.Models.Branch", "Branch")
                        .WithMany("InfoCBNVs")
                        .HasForeignKey("BranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.InsuranceContract", b =>
                {
                    b.HasOne("BaoHiemPhiNhanTho.BackendServer.Models.Customer", "Customer")
                        .WithMany("InsuranceContracts")
                        .HasForeignKey("Cif");

                    b.HasOne("BaoHiemPhiNhanTho.BackendServer.Models.Collateral", "Collateral")
                        .WithMany("InsuranceContracts")
                        .HasForeignKey("CollateralRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaoHiemPhiNhanTho.BackendServer.Models.Partner", "Partner")
                        .WithMany("InsuranceContracts")
                        .HasForeignKey("PartnerCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaoHiemPhiNhanTho.BackendServer.Models.InfoCBNV", "InfoCBNV")
                        .WithMany("InsuranceContracts")
                        .HasForeignKey("TVTTCode");

                    b.Navigation("Collateral");

                    b.Navigation("Customer");

                    b.Navigation("InfoCBNV");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.PaymentPeriod", b =>
                {
                    b.HasOne("BaoHiemPhiNhanTho.BackendServer.Models.InsuranceContract", "InsuranceContract")
                        .WithMany("PaymentPeriods")
                        .HasForeignKey("HDBH");

                    b.Navigation("InsuranceContract");
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.Branch", b =>
                {
                    b.Navigation("InfoCBNVs");
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.Collateral", b =>
                {
                    b.Navigation("InsuranceContracts");
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.Customer", b =>
                {
                    b.Navigation("InsuranceContracts");
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.InfoCBNV", b =>
                {
                    b.Navigation("AnnexContracts");

                    b.Navigation("InsuranceContracts");
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.InsuranceContract", b =>
                {
                    b.Navigation("AnnexContracts");

                    b.Navigation("PaymentPeriods");
                });

            modelBuilder.Entity("BaoHiemPhiNhanTho.BackendServer.Models.Partner", b =>
                {
                    b.Navigation("InsuranceContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
